version: '3.8'

services:
  stt-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - model_data:/app/model_volume
    restart: unless-stopped
    container_name: stt-application
    environment:
      - PYTHONUNBUFFERED=1  # Makes Python output unbuffered for better logging

volumes:
  model_data:
    # This creates a named volume that persists across container restarts